name: Build ViolaLauncher

on:
  push:
    tags:
      - 'v*'  # Triggers workflow on tags like v1.0.21

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Stable for PyInstaller

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller requests certifi

      # 4️⃣ Build launcher .exe
      - name: Build launcher
        run: |
          pyinstaller --noconsole --windowed --onefile --name "Viola Launcher" --icon "src/assets/logo.ico" --add-data "src/assets/logo.ico;assets" --add-data "src/assets/logo.png;assets" --add-data "src/assets/background.png;assets" src/viola_launcher.py

      # 5️⃣ Zip the executable
      - name: Zip executable
        run: |
          mkdir output
          powershell Compress-Archive -Path dist\viola_launcher.exe -DestinationPath output\ViolaLauncher-${{ github.ref_name }}.zip

      # 6️⃣ Calculate SHA256
      - name: Calculate SHA256
        id: hash
        shell: pwsh
        run: |
          $hash = Get-FileHash "output\ViolaLauncher-${{ github.ref_name }}.zip" -Algorithm SHA256
          Write-Output "SHA256=$($hash.Hash)" >> $GITHUB_ENV

      # 7️⃣ Generate latest.json for auto-update
      - name: Generate latest.json
        shell: pwsh
        run: |
          $version = $env:GITHUB_REF_NAME.Substring(1)
          $url = "https://github.com/${{ github.repository }}/releases/download/$env:GITHUB_REF_NAME/ViolaLauncher-$env:GITHUB_REF_NAME.zip"
          $sha256 = $env:SHA256
          $latestJson = @{
            version = $version
            url     = $url
            sha256  = $sha256
            notes   = "Automated build from GitHub Actions."
          } | ConvertTo-Json -Compress
          Set-Content -Path latest.json -Value $latestJson -Encoding UTF8

      # 8️⃣ Optional: list output folder for debugging
      - name: List output folder
        run: dir output

      # 9️⃣ Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            output/ViolaLauncher-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      # 🔟 Upload latest.json as release asset
      - name: Upload latest.json
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: latest.json
          asset_name: latest.json
          asset_content_type: application/json
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
